kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "lingvis.labels" . | nindent 4 }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "lingvis.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lingvis.labels" . | nindent 8 }}
    spec:
      containers:
        - name: tileserver
          image: registry.dbvis.de/jentner/covid-19-vis/tiles:{{ .Values.sha }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: "/health"
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: "/health"
              port: 80
            initialDelaySeconds: 6
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 4
            successThreshold: 1
          resources:
            requesets:
              memory: "500Mi"
              cpu: 0.25
            limits:
              memory: "1000Mi"
              cpu: 0.5
      imagePullSecrets:
          - name: regcred-server
