version: '3'
services:

  gis-backend:
    ports:
      - 5000:5000
    environment:
      - DB_HOST=db.dbvis.de
      - DB_PORT=5432
      - DB_USER=corona
      - DB_PASS=***REMOVED***
      - DB_NAME=coronadb
    build:
      context: ./Backend
      dockerfile: Dockerfile
    volumes:
      - ./Backend/:/var/opt/gis/:z

  gis-frontend:
    image: node:latest
    ports:
      - 4200:4200
    working_dir: /app
    volumes:
      - ./Frontend/gis:/app
    command: sh -c "npm install && npm run start:docker"

volumes: 
  gis-db:
    driver: local
