version: '3'
services:

  gis-backend:
    ports:
      - 5000:5000
    build:
      context: ./Backend
      dockerfile: Dockerfile
    volumes:
      - ./Backend/:/var/opt/gis/:z

  gis-frontend:
    ports:
      - 4200:4200
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    volumes:
      - ./Frontend/gis:/var/opt/gis/:z
    command: sh -c "npm install && npm run start:docker"

volumes: 
  gis-db:
    driver: local
