version: '3'
services:
  gis-database:
    ports:
      - 15432:5432
    build:
      context: ./Database
      dockerfile: Dockerfile

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@gis.com
      - PGADMIN_DEFAULT_PASSWORD=gis_pass
    ports:
      - 8080:80

  gis-backend:
    ports:
      - 5000:5000
    build:
      context: ./Backend
      dockerfile: Dockerfile
    volumes:
      - ./Backend/:/var/opt/gis/

  gis-frontend:
    ports:
      - 4200:4200
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    volumes:
      - ./Frontend/:/var/opt/gis/
