kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "lingvis.labels" . | nindent 4 }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "lingvis.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lingvis.labels" . | nindent 8 }}
    spec:
      containers:
        - name: backend
          image: registry.dbvis.de/jentner/covid-19-vis/backend:{{ .Values.sha }}
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: "/health"
              port: 5000
            initialDelaySeconds: 3
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: "/health"
              port: 5000
            initialDelaySeconds: 6
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 4
            successThreshold: 1
          limits:
            - default:
                memory: 5000M
              defaultRequest:
                memory: 1000M
      imagePullSecrets:
          - name: regcred-server
