# Default values for lingvis-server
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

Group: dbvis
Project: covid-19-vis-tileserver
Branch: master

urlProtocol: https