kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "lingvis.labels" . | nindent 4 }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "lingvis.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lingvis.labels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: registry.dbvis.de/jentner/covid-19-vis/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: FOR_GODS_SAKE_PLEASE_REDEPLOY
              value: {{ .Values.uuid | quote }}
          readinessProbe:
            httpGet:
              path: "/"
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: "/"
              port: 80
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 4
            successThreshold: 1
          limits:
            - default:
                memory: 200M
              defaultRequest:
                memory: 50M
        - name: backend
          image: registry.dbvis.de/jentner/covid-19-vis/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: FOR_GODS_SAKE_PLEASE_REDEPLOY
              value: {{ .Values.uuid | quote }}
          readinessProbe:
            httpGet:
              path: "/health"
              port: 8000
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: "/health"
              port: 8000
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 4
            successThreshold: 1
          limits:
            - default:
                memory: 5000M
              defaultRequest:
                memory: 1000M
      imagePullSecrets:
          - name: regcred-server
