apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: covid19vis-crawler-rki-lk-bl-cases
  annotations:
    description: "RKI cases on LK and BL level aggregated"
spec:
  # run at 9am
  schedule: "0 9 * * *"
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
          - name: covid19vis-crawler-rki-lk-bl-cases
            image: registry.dbvis.de/jentner/covid-19-vis/crawler:{{ .Values.sha }}
            imagePullPolicy: Always
            command: ['python']
            args: ['crawler_rki_dashboard.py']
          restartPolicy: Never
          imagePullSecrets:
            - name: regcred-server