apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: covid19vis-crawler
  description: "unknown"  
spec:
  # run every four hours
  schedule: "0 */4 * * *"
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
          - name: covid19vis-crawler
            image: registry.dbvis.de/jentner/covid-19-vis/crawler:{{ .Values.sha }}
            imagePullPolicy: Always
            command: ['python']
            args: ['crawler.py']
          restartPolicy: Never
          imagePullSecrets:
            - name: regcred-server

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: covid19vis-crawler-map
  description: "RKI map aggregate unknown"  
spec:
  # run at 9am
  schedule: "0 9 * * *"
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
          - name: covid19vis-crawler-map
            image: registry.dbvis.de/jentner/covid-19-vis/crawler:{{ .Values.sha }}
            imagePullPolicy: Always
            command: ['python']
            args: ['crawler_map.py']
          restartPolicy: Never
          imagePullSecrets:
            - name: regcred-server

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: covid19vis-crawler-rki
  description: "RKI unknown"
spec:
  # run at 9am
  schedule: "0 9 * * *"
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
          - name: covid19vis-crawler-rki
            image: registry.dbvis.de/jentner/covid-19-vis/crawler:{{ .Values.sha }}
            imagePullPolicy: Always
            command: ['python']
            args: ['crawler_rki_dashboard.py']
          restartPolicy: Never
          imagePullSecrets:
            - name: regcred-server

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: covid19vis-crawler-cases
  description: "RKI individual cases including statistical information per patient"
spec:
  # run at 9am
  schedule: "0 9 * * *"
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
          - name: covid19vis-crawler-cases
            image: registry.dbvis.de/jentner/covid-19-vis/crawler:{{ .Values.sha }}
            imagePullPolicy: Always
            command: ['python']
            args: ['crawl_rki_cases.py']
          restartPolicy: Never
          imagePullSecrets:
            - name: regcred-server
            
---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: covid19vis-crawler-divi
  description: "DIVI Intensivregister detailed bed count per hospital (actual numbers, not colors)"
spec:
  # run at 9am
  schedule: "0 9 * * *"
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
          - name: covid19vis-crawler-divi
            image: registry.dbvis.de/jentner/covid-19-vis/crawler:{{ .Values.sha }}
            imagePullPolicy: Always
            command: ['python']
            args: ['crawl_divi_data.py']
          restartPolicy: Never
          imagePullSecrets:
            - name: regcred-server
